### 基本语法
### 语言问题：https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [2]:
import torch
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

#### 第一步，导入张量tensor

In [7]:
#1.直接导入
a=[[1,2],[3,4],[5,6]]
a_tensor=torch.tensor(a)

In [46]:
#2.从numpy转来，本质共享内存位置，同步改变
b=np.array([[1,2],[3,4],[5,6]])
b_tensor=torch.from_numpy(b)

In [9]:
a_tensor,b_tensor

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [10]:
#3.仿照或者重写自一个已存在的tensor
c_tensor=torch.ones_like(a_tensor)  #构建一个和a_tensor同形状的tensor
c_tensor

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [11]:
d_tensor=torch.rand_like(b_tensor,dtype=float)    #构建一个和b_tensor同形状的数据类型为浮点数的张量
d_tensor

tensor([[0.3397, 0.1553],
        [0.5416, 0.5197],
        [0.5473, 0.3593]], dtype=torch.float64)

#### 第二，张量属性


In [12]:
#shape来构建张量
shape=(3,4)
e_tensor=torch.rand(shape)
e_tensor

tensor([[0.7698, 0.7338, 0.3529, 0.4304],
        [0.6029, 0.8900, 0.0195, 0.2995],
        [0.4313, 0.0688, 0.7987, 0.7220]])

In [13]:
f_tor=torch.ones(shape)
g_tor=torch.zeros(shape)
f_tor,g_tor

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [14]:
#或者直接使用形状来调用
f_tor=torch.rand(5,6)
g_tor=torch.ones(10,10)
f_tor,g_tor

(tensor([[0.3952, 0.2226, 0.7138, 0.6226, 0.8771, 0.2588],
         [0.8228, 0.7052, 0.8942, 0.8824, 0.8155, 0.3736],
         [0.8996, 0.9275, 0.3349, 0.6158, 0.2213, 0.8860],
         [0.2820, 0.0862, 0.7597, 0.6837, 0.8493, 0.1977],
         [0.2626, 0.6895, 0.6671, 0.3176, 0.4230, 0.3623]]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

#### 第三，tensor操作

In [16]:
tensor=torch.rand(3,3)

##### 1.装载

In [18]:
#1.将内存中的张量装载到gpu上
#识别当前加速器类型
device=torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor=tensor.to(device)
print(f"Device tensor is stored on:{tensor.device}")

Device tensor is stored on:cuda:0


##### 2.设置张量

In [24]:
#2.设置张量的行列值
h=torch.ones(3,3)

i=h
r=torch.clone(h)

h[:,1]=114
i[2,2]=514
i,h,r

(tensor([[  1., 114.,   1.],
         [  1., 114.,   1.],
         [  1., 114., 514.]]),
 tensor([[  1., 114.,   1.],
         [  1., 114.,   1.],
         [  1., 114., 514.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

#### 这里i与h内容完全一致，是因为pytorch的=符号相当于i、h共享同一个张量内存
##### 而如果想克隆（复制）同样的张量，则需要使用.clone()

##### 3.张量拼接

In [28]:
#3.张量拼接
#dim=1横向拼接
#dim=0纵向拼接
r=torch.cat([h,h,h],dim=1)
s=torch.cat([h,h,h],dim=0)#即使是纵向拼接也给出张量列表即可，列表只是给出拼接的张量名字，而非最终的拼接形式
r,s

(tensor([[  1., 114.,   1.,   1., 114.,   1.,   1., 114.,   1.],
         [  1., 114.,   1.,   1., 114.,   1.,   1., 114.,   1.],
         [  1., 114., 514.,   1., 114., 514.,   1., 114., 514.]]),
 tensor([[  1., 114.,   1.],
         [  1., 114.,   1.],
         [  1., 114., 514.],
         [  1., 114.,   1.],
         [  1., 114.,   1.],
         [  1., 114., 514.],
         [  1., 114.,   1.],
         [  1., 114.,   1.],
         [  1., 114., 514.]]))

##### 4.张量相乘（基本与numpy一致）
* *同形状张量逐元素相乘,相乘结果仍为该元素（cnn rnn常用）
* @ matmul矩阵乘法

In [45]:
print(a)
print(f"a_tensor*a_tensor:{a_tensor*a_tensor}")
print(f"a_tensor@a_tensor:{a_tensor@a_tensor.T}")##一定注意转置
print(f"matmul:{torch.matmul(a_tensor,a_tensor.T)}")

#matmul另一种调用形式
print(f"matmul second:{a_tensor.matmul(a_tensor.T)}")

[[1, 2], [3, 4], [5, 6]]
a_tensor*a_tensor:tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])
a_tensor@a_tensor:tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])
matmul:tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])
matmul second:tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])


#### 5 .tensor与numpy.array相互转化

In [47]:
#from_numpy本质也是内存共享，所以会同步改变
b=np.array([[1,2],[3,4],[5,6]])
b_tensor=torch.from_numpy(b)