In [44]:
import torch
from torch import nn
import torch.nn.functional as F 

In [45]:
x=torch.arange(4) 
x

tensor([0, 1, 2, 3])

In [46]:
#file save&load:
torch.save(x,'x-file')
x1=torch.load('x-file')
x1

tensor([0, 1, 2, 3])

In [47]:
y=torch.zeros(5)
torch.save((x,y),'x-file')
x2,y2=torch.load('x-file')
x2,y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0., 0.]))

save model ->save the model's parameter

In [48]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,x):
        return F.relu(self.output(self.hidden(x)))

net=MLP()
x=torch.rand(2,20)
y=net(x)

In [49]:
#save model's state_dict() (parameters as well)
torch.save(net.state_dict(),'mlp.params')

#load the model
clone=MLP()
clone.load_state_dict(torch.load('mlp.params')) #write back the saved parameters to new model "clone"
                                                #use function "load_state_dict()"
clone.eval()  #change to evalaute mode (for reasoning mode)



#RESONING MODE(TEST MODE):
# with torch.no_grad():
#    output=clone(test_data)

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [50]:
y_clone=clone(x)
y_clone==y        # between 2 tensor
#y_clone==net XXXXX  because y_clone is a tensor while net is an object

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])