In [3]:
!pip install "numpy>=1.24" d2l



[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import torch
from torch import nn
from d2l import torch as d2l

In [5]:
'''The idea is to first determine the shape of the result Y, and then simulate the pooling process to fill Y.'''
'''the calculate of Y_shape is same as the pocess of convolution_output_shape: ((x_h+pad_h-p_h)/s_h+1)*((x_w+pad_w-p_w)/s_w+1)'''
def pool2d(X,pool_size,mode='max'):
    p_h,p_w=pool_size
    #Y is the result of pooling  (x_h-p_h+1)*(x_w-p_w+1)
    Y=torch.zeros((X.shape[0]-p_h+1),(X.shape[1]-p_w+1))

    #pooling:
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j]=X[i:i+p_h,j:j+p_w].max()
            if mode=='avg':
                Y[i,j]=X[i:i+p_h,j:j+p_w].mean()
        
    return Y 

In [6]:
X=torch.tensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
pool2d(X,(2,2)),pool2d(X,(2,2),'avg')

(tensor([[5., 6.],
         [8., 9.]]),
 tensor([[3., 4.],
         [6., 7.]]))

In [11]:
#padding and stride
#we need to reshape a 2d tensor to a 4d tensor([[[[X]]]])
X=torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [13]:
pool=nn.MaxPool2d(3)  #Default stride equals kernel size. kernel_size=stride=3,default_padding=0
pool(X)

tensor([[[[10.]]]])

In [17]:
pool1=nn.MaxPool2d(kernel_size=3,stride=1,padding=1)  #Manually set stride and padding
pool1(X)

tensor([[[[ 5.,  6.,  7.,  7.],
          [ 9., 10., 11., 11.],
          [13., 14., 15., 15.],
          [13., 14., 15., 15.]]]])

In [16]:
pool2=nn.MaxPool2d(kernel_size=3)  #Manually set kernel_size
pool2(X)

tensor([[[[10.]]]])

In [23]:
pool3=nn.MaxPool2d(kernel_size=(2,3),stride=2,padding=1)  #Manually  set Asymmetric stride and padding
pool3(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]],

         [[ 3.,  5.],
          [11., 13.],
          [15., 17.]]]])

### 在python/pytorch中，调用函数的时候的实参调用方法：  
#### 1.位置参数：只需要传入具体类型的实参，但位置必须与函数定义时的形参顺序严格一致
## 2.关键词参数：“形参=实参”的形式显式指定实参，但顺序无关

In [25]:
# pooling in multi_channels
X=torch.cat((X,X+1),1)  # cat X and X+1 by X's first dim——the channel_dim
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]],

         [[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.],
          [14., 15., 16., 17.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]],

         [[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.],
          [14., 15., 16., 17.]],

         [[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.],
          [14., 15., 16., 17.]],

         [[ 3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10.],
          [11., 12., 13., 

In [26]:
pool3(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]],

         [[ 3.,  5.],
          [11., 13.],
          [15., 17.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]],

         [[ 3.,  5.],
          [11., 13.],
          [15., 17.]],

         [[ 3.,  5.],
          [11., 13.],
          [15., 17.]],

         [[ 4.,  6.],
          [12., 14.],
          [16., 18.]]]])